# -*- coding: utf-8 -*-
"""
Created on Wed Apr  4 18:44:23 2020

@author: Daniel Mastropietro
@description: Definition of classes defining agents.
Each agent is created with a policy and a learner class and implements the following methods:
    - getPolicy()
    - getLearner()
"""

# If below we use `import *` we get a warning generated by Spyder: "unable to detect undefined names"
# This is due to the fact that it doesn't know which modules are being imported, because they are not listed.
# It seems we can disable the warnings by adding the comment #NOQA but it doesn't work.
# Ref: https://stackoverflow.com/questions/50439309/spyder-ide-complaining-about-unable-to-detect-undefined-names
# where they actually also mention that it is a common pattern to do this import * in an __init__.py file!
#from .policies.random_walks import PolRandomWalkDiscrete
#from .learners.td_lambda import LeaTDLambda


class GeneralAgent:
    "Class that holds the information of the policy and the learner associated to the agent"

    def __init__(self, policy, learner):
        self.policy = policy
        self.learner = learner
    
    def getPolicy(self):
        return self.policy

    def getLearner(self):
        return self.learner
